-- MySQL Script generated by MySQL Workbench
-- Tue May  9 09:05:23 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kairos_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kairos_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kairos_db` DEFAULT CHARACTER SET utf8 ;
USE `kairos_db` ;

-- -----------------------------------------------------
-- Table `kairos_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kairos_db`.`user` ;

CREATE TABLE IF NOT EXISTS `kairos_db`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_pseudo` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(40) NOT NULL,
  `user_mail` VARCHAR(254) NOT NULL,
  `user_isAdmin` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kairos_db`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kairos_db`.`project` ;

CREATE TABLE IF NOT EXISTS `kairos_db`.`project` (
  `project_id` INT NOT NULL AUTO_INCREMENT,
  `project_title` VARCHAR(45) NOT NULL,
  `project_description` VARCHAR(500) NULL,
  `project_dateCreation` DATETIME NOT NULL,
  `project_dateClosed` DATETIME NULL,
  `project_plannedBeginning` DATETIME NULL,
  `project_plannedEnd` DATETIME NULL,
  `project_isClosed` TINYINT(1) NOT NULL DEFAULT 0,
  `user_fk` INT NOT NULL,
  PRIMARY KEY (`project_id`),
  INDEX `fk_project_user_idx` (`user_fk` ASC),
  CONSTRAINT `fk_project_user`
    FOREIGN KEY (`user_fk`)
    REFERENCES `kairos_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kairos_db`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kairos_db`.`task` ;

CREATE TABLE IF NOT EXISTS `kairos_db`.`task` (
  `task_id` INT NOT NULL AUTO_INCREMENT,
  `task_title` VARCHAR(45) NOT NULL,
  `task_description` VARCHAR(500) NULL,
  `task_timePassed` TIME(1) NULL,
  `task_dateCreation` DATETIME NOT NULL,
  `task_dateClosed` DATETIME NULL,
  `task_plannedBeginning` DATETIME NULL,
  `task_plannedEnd` DATETIME NULL,
  `task_isClosed` TINYINT(1) NOT NULL DEFAULT 0,
  `project_fk` INT NOT NULL,
  PRIMARY KEY (`task_id`),
  INDEX `fk_task_project1_idx` (`project_fk` ASC),
  CONSTRAINT `fk_task_project1`
    FOREIGN KEY (`project_fk`)
    REFERENCES `kairos_db`.`project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kairos_db`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kairos_db`.`comment` ;

CREATE TABLE IF NOT EXISTS `kairos_db`.`comment` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `comment_content` VARCHAR(200) NOT NULL,
  `comment_date` DATETIME NOT NULL,
  `task_fk` INT NOT NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `fk_comment_task1_idx` (`task_fk` ASC),
  CONSTRAINT `fk_comment_task1`
    FOREIGN KEY (`task_fk`)
    REFERENCES `kairos_db`.`task` (`task_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
